#!/usr/bin/env bash

printf "[ %s: Prepare velvetg hash files with velveth ]\n" \
    "$(date)"

# shellcheck disable=SC1091
source "src/sh/bash_header"
# shellcheck disable=SC1091
source "src/sh/io_parser"

# make outdir
outdir="$(dirname "${other_output}")"
outdir="${outdir//_*/}"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# set number of processors (doesn't work on biochemcompute)
# export OMP_THREAD_LIMIT="${max_cpus}"

# set velveth binary
my_velveth="bin/velvet/velveth"

# separate the input fq by library typew
for fq_file in "${input_fq[@]}"; do
    bn="$(basename "${fq_file}" .fastq.gz)"
    if grep -q "2125-06-11-1" <<< "${bn}"; then
        ifq="${fq_file}"
    elif grep -q "_pe_" <<< "${bn}"; then
        ifq_pe="${fq_file}"
    elif grep -q "_se_" <<< "${bn}"; then
        ifq_se="${fq_file}"
    elif grep -q "_mp_" <<< "${bn}"; then
        ifq_mp="${fq_file}"
    elif grep -q "_unknown_" <<< "${bn}"; then
        ifq_unk="${fq_file}"
    fi
done

printf "\tifq: %s\n" "${ifq}"
printf "\tifq_pe: %s\n" "${ifq_pe}"
printf "\tifq_se: %s\n" "${ifq_se}"
printf "\tifq_mp: %s\n" "${ifq_mp}"
printf "\tifq_unk: %s\n" "${ifq_unk}"

# parameters
 maxkmerlength="87"
 minkmerlength="71"
          step="8"

# build command
cmd=( "${my_velveth}" "${outdir}"
      "${minkmerlength},$(( maxkmerlength + 1 )),${step}"
      -short        -fastq           "${ifq_se}"
      -shortPaired  -fastq "${ifq}"
      -shortPaired2 -fastq "${ifq_pe}"
      -shortPaired3 -fastq "${ifq_mp}"
      -shortPaired4 -fastq "${ifq_unk}"
      -create_binary )
shopt -s extglob
printf "Final command line: "
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

# run velveth
log_file="${outdir}/velveth.log.txt"
"${cmd[@]}" &> "${log_file}" &

printf "[ %s: Waiting for velveth to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/METADATA.csv"

printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    velveth,$("${my_velveth}" 2>&1 | sed '2q;d')
    output,${outdir}
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0
